//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOBLE_SALE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NOBLE_SALE.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code.
        /// </summary>
        internal static string Account_Code {
            get {
                return ResourceManager.GetString("Account Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT LEDGER.
        /// </summary>
        internal static string Account_Ledger {
            get {
                return ResourceManager.GetString("Account Ledger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string Account_Ledger_Icon {
            get {
                return ResourceManager.GetString("Account Ledger Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Setup.
        /// </summary>
        internal static string Account_Setup {
            get {
                return ResourceManager.GetString("Account Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        internal static string Account_Type {
            get {
                return ResourceManager.GetString("Account Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string Active_Terminal_Icon {
            get {
                return ResourceManager.GetString("Active Terminal Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE TERMINALS.
        /// </summary>
        internal static string Active_Terminals {
            get {
                return ResourceManager.GetString("Active Terminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW.
        /// </summary>
        internal static string Add_New {
            get {
                return ResourceManager.GetString("Add New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW EMPLOYEE.
        /// </summary>
        internal static string Add_New_Employee {
            get {
                return ResourceManager.GetString("Add New Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required.
        /// </summary>
        internal static string Address_is_required {
            get {
                return ResourceManager.GetString("Address is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Info.
        /// </summary>
        internal static string Admin_Info {
            get {
                return ResourceManager.GetString("Admin Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the.
        /// </summary>
        internal static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow All.
        /// </summary>
        internal static string Allow_All {
            get {
                return ResourceManager.GetString("Allow All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow All Invoices.
        /// </summary>
        internal static string Allow_All_Invoices {
            get {
                return ResourceManager.GetString("Allow All Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Start Expense Operation.
        /// </summary>
        internal static string Allow_Start_Expense_Operation {
            get {
                return ResourceManager.GetString("Allow Start Expense Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed to Change Price During Sale.
        /// </summary>
        internal static string Allowed_to_Change_Price_During_Sale {
            get {
                return ResourceManager.GetString("Allowed to Change Price During Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed to Close Counter.
        /// </summary>
        internal static string Allowed_to_Close_Counter {
            get {
                return ResourceManager.GetString("Allowed to Close Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed to Close Day.
        /// </summary>
        internal static string Allowed_to_Close_Day {
            get {
                return ResourceManager.GetString("Allowed to Close Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed to Give Discount During Sale.
        /// </summary>
        internal static string Allowed_to_Give_Discount_During_Sale {
            get {
                return ResourceManager.GetString("Allowed to Give Discount During Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed to Hold Counter.
        /// </summary>
        internal static string Allowed_to_Hold_Counter {
            get {
                return ResourceManager.GetString("Allowed to Hold Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed to Process Sale Return.
        /// </summary>
        internal static string Allowed_to_Process_Sale_Return {
            get {
                return ResourceManager.GetString("Allowed to Process Sale Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed to Start Day.
        /// </summary>
        internal static string Allowed_to_Start_Day {
            get {
                return ResourceManager.GetString("Allowed to Start Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed to Transfer Counter.
        /// </summary>
        internal static string Allowed_to_Transfer_Counter {
            get {
                return ResourceManager.GetString("Allowed to Transfer Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed to Use Daily Expense List.
        /// </summary>
        internal static string Allowed_to_Use_Daily_Expense_List {
            get {
                return ResourceManager.GetString("Allowed to Use Daily Expense List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed to View Counter Details.
        /// </summary>
        internal static string Allowed_to_View_Counter_Details {
            get {
                return ResourceManager.GetString("Allowed to View Counter Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Transaction.
        /// </summary>
        internal static string Allowed_Transaction {
            get {
                return ResourceManager.GetString("Allowed Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name Required.
        /// </summary>
        internal static string Arabic_Name_Required {
            get {
                return ResourceManager.GetString("Arabic Name Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        internal static string Assets {
            get {
                return ResourceManager.GetString("Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSIGN USER.
        /// </summary>
        internal static string Assign_User {
            get {
                return ResourceManager.GetString("Assign User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Price.
        /// </summary>
        internal static string Avg_Price {
            get {
                return ResourceManager.GetString("Avg Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance .
        /// </summary>
        internal static string Balance_Report {
            get {
                return ResourceManager.GetString("Balance Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Sheet Report.
        /// </summary>
        internal static string Balance_Sheet_Report {
            get {
                return ResourceManager.GetString("Balance Sheet Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BANK.
        /// </summary>
        internal static string BANK {
            get {
                return ResourceManager.GetString("BANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string BankHistory {
            get {
                return ResourceManager.GetString("BankHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string BankLower {
            get {
                return ResourceManager.GetString("BankLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUSINESS LICENSE DETAIL.
        /// </summary>
        internal static string Business_License_History {
            get {
                return ResourceManager.GetString("Business License History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        internal static string Business_Name {
            get {
                return ResourceManager.GetString("Business Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name Required.
        /// </summary>
        internal static string Business_Name_Required {
            get {
                return ResourceManager.GetString("Business Name Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type.
        /// </summary>
        internal static string Business_Type {
            get {
                return ResourceManager.GetString("Business Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type is required.
        /// </summary>
        internal static string Business_Type_is_required {
            get {
                return ResourceManager.GetString("Business Type is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUSINESSES.
        /// </summary>
        internal static string Businesses {
            get {
                return ResourceManager.GetString("Businesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string Businesses_Icon {
            get {
                return ResourceManager.GetString("Businesses Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not be empty!.
        /// </summary>
        internal static string Can_not_be_empty {
            get {
                return ResourceManager.GetString("Can not be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carry Cash.
        /// </summary>
        internal static string Carry_Cash {
            get {
                return ResourceManager.GetString("Carry Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASH.
        /// </summary>
        internal static string CASH {
            get {
                return ResourceManager.GetString("CASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Counter.
        /// </summary>
        internal static string Cash_Counter {
            get {
                return ResourceManager.GetString("Cash Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASH COUNTER DETAILS.
        /// </summary>
        internal static string Cash_Counter_Details {
            get {
                return ResourceManager.GetString("Cash Counter Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string Cash_Counter_Icon {
            get {
                return ResourceManager.GetString("Cash Counter Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash in Hand.
        /// </summary>
        internal static string Cash_in_Hand {
            get {
                return ResourceManager.GetString("Cash in Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is Required.
        /// </summary>
        internal static string Category_is_Required {
            get {
                return ResourceManager.GetString("Category is Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        internal static string Category_Name {
            get {
                return ResourceManager.GetString("Category Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string CDP_icon {
            get {
                return ResourceManager.GetString("CDP icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLIENT MANAGEMENT.
        /// </summary>
        internal static string Client_Management {
            get {
                return ResourceManager.GetString("Client Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Number.
        /// </summary>
        internal static string Client_number {
            get {
                return ResourceManager.GetString("Client number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLIENTS.
        /// </summary>
        internal static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string Clients_Icon {
            get {
                return ResourceManager.GetString("Clients Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANIES.
        /// </summary>
        internal static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string Companies_Icon {
            get {
                return ResourceManager.GetString("Companies Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY LICENSE HISTORY.
        /// </summary>
        internal static string Company_License_Detail {
            get {
                return ResourceManager.GetString("Company License Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string Company_Name {
            get {
                return ResourceManager.GetString("Company Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name is required.
        /// </summary>
        internal static string Company_Name_is_required {
            get {
                return ResourceManager.GetString("Company Name is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        internal static string Confirm_New_Password {
            get {
                return ResourceManager.GetString("Confirm New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2021 NoblePOS.
        /// </summary>
        internal static string Copyright1 {
            get {
                return ResourceManager.GetString("Copyright1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        internal static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string CPS_icon {
            get {
                return ResourceManager.GetString("CPS icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Name.
        /// </summary>
        internal static string Currency_Name {
            get {
                return ResourceManager.GetString("Currency Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Name is required.
        /// </summary>
        internal static string Currency_Name_is_required {
            get {
                return ResourceManager.GetString("Currency Name is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Sign.
        /// </summary>
        internal static string Currency_Sign {
            get {
                return ResourceManager.GetString("Currency Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Sign is required.
        /// </summary>
        internal static string Currency_sign_is_required {
            get {
                return ResourceManager.GetString("Currency sign is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string Current_Password {
            get {
                return ResourceManager.GetString("Current Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Qty.
        /// </summary>
        internal static string Current_Qty {
            get {
                return ResourceManager.GetString("Current Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Year Earnings.
        /// </summary>
        internal static string Current_Year_Earnings {
            get {
                return ResourceManager.GetString("Current Year Earnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Balance Report.
        /// </summary>
        internal static string Customer_Balance_Report {
            get {
                return ResourceManager.GetString("Customer Balance Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMER DISCOUNT PRODUCTS.
        /// </summary>
        internal static string Customer_Discount_Products {
            get {
                return ResourceManager.GetString("Customer Discount Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Ledger Report.
        /// </summary>
        internal static string Customer_Ledger_Report {
            get {
                return ResourceManager.GetString("Customer Ledger Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMER PRODUCT SALE.
        /// </summary>
        internal static string Customer_Product_Sale {
            get {
                return ResourceManager.GetString("Customer Product Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Wise Products Sale.
        /// </summary>
        internal static string Customer_Wise_Products_Sale {
            get {
                return ResourceManager.GetString("Customer Wise Products Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers Wise Product Sale.
        /// </summary>
        internal static string Customers_Wise_Product_Sale {
            get {
                return ResourceManager.GetString("Customers Wise Product Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DASHBOARD.
        /// </summary>
        internal static string DASHBOARD {
            get {
                return ResourceManager.GetString("DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAY COUNTER.
        /// </summary>
        internal static string Day_Counter {
            get {
                return ResourceManager.GetString("Day Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAY START.
        /// </summary>
        internal static string Day_Start {
            get {
                return ResourceManager.GetString("Day Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Wise Report.
        /// </summary>
        internal static string Day_Wise_Report {
            get {
                return ResourceManager.GetString("Day Wise Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAILS.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dis %.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amount.
        /// </summary>
        internal static string Discount_Amount {
            get {
                return ResourceManager.GetString("Discount Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string Dont_have_an_account {
            get {
                return ResourceManager.GetString("Dont have an account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPLOYEE.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Code.
        /// </summary>
        internal static string Employee_Code {
            get {
                return ResourceManager.GetString("Employee Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string Employee_Icon {
            get {
                return ResourceManager.GetString("Employee Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        internal static string Employee_Name {
            get {
                return ResourceManager.GetString("Employee Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending date.
        /// </summary>
        internal static string Ending_date {
            get {
                return ResourceManager.GetString("Ending date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name Required.
        /// </summary>
        internal static string English_Name_Required {
            get {
                return ResourceManager.GetString("English Name Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid IP address.
        /// </summary>
        internal static string Enter_a_valid_IP_address {
            get {
                return ResourceManager.GetString("Enter a valid IP address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid port number.
        /// </summary>
        internal static string Enter_a_valid_port_number {
            get {
                return ResourceManager.GetString("Enter a valid port number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid tax rate.
        /// </summary>
        internal static string Enter_a_valid_tax_rate {
            get {
                return ResourceManager.GetString("Enter a valid tax rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email &amp; password to continue.
        /// </summary>
        internal static string Enter_email_pass {
            get {
                return ResourceManager.GetString("Enter email pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Port &amp; IP to continue.
        /// </summary>
        internal static string Enter_Port_IP {
            get {
                return ResourceManager.GetString("Enter Port IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equity.
        /// </summary>
        internal static string Equity {
            get {
                return ResourceManager.GetString("Equity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPENSES.
        /// </summary>
        internal static string EXPENSE {
            get {
                return ResourceManager.GetString("EXPENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        internal static string ExpenseHistory {
            get {
                return ResourceManager.GetString("ExpenseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        internal static string ExpenseLower {
            get {
                return ResourceManager.GetString("ExpenseLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string First_Name {
            get {
                return ResourceManager.GetString("First Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Discount.
        /// </summary>
        internal static string Fixed_Discount {
            get {
                return ResourceManager.GetString("Fixed Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string FOCP_icon {
            get {
                return ResourceManager.GetString("FOCP icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string FOCS_icon {
            get {
                return ResourceManager.GetString("FOCS icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREE OF COST PURCHASE.
        /// </summary>
        internal static string Free_Of_Cost_Purchase {
            get {
                return ResourceManager.GetString("Free Of Cost Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREE OF COST SALE.
        /// </summary>
        internal static string Free_Of_Cost_Sale {
            get {
                return ResourceManager.GetString("Free Of Cost Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string From_Date {
            get {
                return ResourceManager.GetString("From Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender*.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Select Gender.
        /// </summary>
        internal static string Gender_Required {
            get {
                return ResourceManager.GetString("Gender Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Locations.
        /// </summary>
        internal static string Get_Locations {
            get {
                return ResourceManager.GetString("Get Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Warehouses.
        /// </summary>
        internal static string Get_Warehouses {
            get {
                return ResourceManager.GetString("Get Warehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello there,.
        /// </summary>
        internal static string Greeting1 {
            get {
                return ResourceManager.GetString("Greeting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back!.
        /// </summary>
        internal static string Greeting2 {
            get {
                return ResourceManager.GetString("Greeting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR MANAGEMENT.
        /// </summary>
        internal static string HR_Management {
            get {
                return ResourceManager.GetString("HR Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string I {
            get {
                return ResourceManager.GetString("I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID*.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (If Available).
        /// </summary>
        internal static string If_Available {
            get {
                return ResourceManager.GetString("If Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string InActive_Terminal_Icon {
            get {
                return ResourceManager.GetString("InActive Terminal Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN-ACTIVE TERMINALS.
        /// </summary>
        internal static string InActive_Terminals {
            get {
                return ResourceManager.GetString("InActive Terminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Statement Report.
        /// </summary>
        internal static string Income_Statement_Report {
            get {
                return ResourceManager.GetString("Income Statement Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        internal static string Invalid_Email {
            get {
                return ResourceManager.GetString("Invalid Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        internal static string Invalid_Password {
            get {
                return ResourceManager.GetString("Invalid Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVENTORY.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Count.
        /// </summary>
        internal static string Inventory_Count {
            get {
                return ResourceManager.GetString("Inventory Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Count List.
        /// </summary>
        internal static string Inventory_Count_List {
            get {
                return ResourceManager.GetString("Inventory Count List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Filter Report.
        /// </summary>
        internal static string Inventory_Report {
            get {
                return ResourceManager.GetString("Inventory Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Stock Report.
        /// </summary>
        internal static string Inventory_Stock_Report {
            get {
                return ResourceManager.GetString("Inventory Stock Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice W/O Inventory.
        /// </summary>
        internal static string Invoice_W_O_Inventory {
            get {
                return ResourceManager.GetString("Invoice W/O Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        internal static string Is_Active {
            get {
                return ResourceManager.GetString("Is Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Supervisor.
        /// </summary>
        internal static string Is_Supervisor {
            get {
                return ResourceManager.GetString("Is Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land line.
        /// </summary>
        internal static string Landline {
            get {
                return ResourceManager.GetString("Landline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Last_Name {
            get {
                return ResourceManager.GetString("Last Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liabilities.
        /// </summary>
        internal static string Liabilities {
            get {
                return ResourceManager.GetString("Liabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LICENSE DETAIL.
        /// </summary>
        internal static string License_Detail {
            get {
                return ResourceManager.GetString("License Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf/Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Email.
        /// </summary>
        internal static string Location_Email {
            get {
                return ResourceManager.GetString("Location Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCATION LICENSE HISTORY.
        /// </summary>
        internal static string Location_License_History {
            get {
                return ResourceManager.GetString("Location License History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCATIONS.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string Locations_Icon {
            get {
                return ResourceManager.GetString("Locations Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string Log_Out {
            get {
                return ResourceManager.GetString("Log Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE.
        /// </summary>
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone Number is Required.
        /// </summary>
        internal static string Mobile_Number_Required {
            get {
                return ResourceManager.GetString("Mobile Number Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY SETTINGS.
        /// </summary>
        internal static string My_Settings {
            get {
                return ResourceManager.GetString("My Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Arabic).
        /// </summary>
        internal static string Name_Arabic {
            get {
                return ResourceManager.GetString("Name Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (English).
        /// </summary>
        internal static string Name_English {
            get {
                return ResourceManager.GetString("Name English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narration.
        /// </summary>
        internal static string Narration {
            get {
                return ResourceManager.GetString("Narration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOBLE-POS.
        /// </summary>
        internal static string NOBLEPOS {
            get {
                return ResourceManager.GetString("NOBLEPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to show.
        /// </summary>
        internal static string Nothing_to_show {
            get {
                return ResourceManager.GetString("Nothing to show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening.
        /// </summary>
        internal static string Opening {
            get {
                return ResourceManager.GetString("Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Cash.
        /// </summary>
        internal static string Opening_Cash {
            get {
                return ResourceManager.GetString("Opening Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Cash.
        /// </summary>
        internal static string OPENINGCASH {
            get {
                return ResourceManager.GetString("OPENINGCASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum eight characters, at least one uppercase letter, one lowercase letter and one number.
        /// </summary>
        internal static string Passoword_Auth {
            get {
                return ResourceManager.GetString("Passoword Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least one number [0-9], one lowercase letter [a-z], one uppercase letter [A-Z], at least one special character and at least 8 characters in length..
        /// </summary>
        internal static string Password_Detail {
            get {
                return ResourceManager.GetString("Password Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Do Not Match.
        /// </summary>
        internal static string Password_Do_Not_Match {
            get {
                return ResourceManager.GetString("Password Do Not Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string PDC_icon {
            get {
                return ResourceManager.GetString("PDC icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string PDS_icon {
            get {
                return ResourceManager.GetString("PDS icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMISSIONS.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMISSIONS FOR.
        /// </summary>
        internal static string Permissions_for {
            get {
                return ResourceManager.GetString("Permissions for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string Permissions_Icon {
            get {
                return ResourceManager.GetString("Permissions Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Quantity.
        /// </summary>
        internal static string Physical_Quantity {
            get {
                return ResourceManager.GetString("Physical Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Network Details.
        /// </summary>
        internal static string Please_Enter_Network_Details {
            get {
                return ResourceManager.GetString("Please Enter Network Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS-RETAIL.
        /// </summary>
        internal static string POS_Retail {
            get {
                return ResourceManager.GetString("POS-Retail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT DETAILS.
        /// </summary>
        internal static string Product_Details {
            get {
                return ResourceManager.GetString("Product Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT DISCOUNT CUSTOMERS.
        /// </summary>
        internal static string Product_Discount_Customers {
            get {
                return ResourceManager.GetString("Product Discount Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT DISCOUNT SUPPLIERS.
        /// </summary>
        internal static string Product_Discount_Suppliers {
            get {
                return ResourceManager.GetString("Product Discount Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Inventory Report.
        /// </summary>
        internal static string Product_Inventory_Report {
            get {
                return ResourceManager.GetString("Product Inventory Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Local Store.
        /// </summary>
        internal static string Product_Local_Store {
            get {
                return ResourceManager.GetString("Product Local Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string Product_Name {
            get {
                return ResourceManager.GetString("Product Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT SALE CUSTOMERS.
        /// </summary>
        internal static string Product_Sale_Customers {
            get {
                return ResourceManager.GetString("Product Sale Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT SALE TO SUPPLIER.
        /// </summary>
        internal static string Product_Sale_Supplier_Wise {
            get {
                return ResourceManager.GetString("Product Sale Supplier Wise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Stock Value.
        /// </summary>
        internal static string Product_Stock_Value {
            get {
                return ResourceManager.GetString("Product Stock Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Stock Avg Value.
        /// </summary>
        internal static string Product_Stock_Value_Average {
            get {
                return ResourceManager.GetString("Product Stock Value Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Settings.
        /// </summary>
        internal static string Profile_Settings {
            get {
                return ResourceManager.GetString("Profile Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string PSC_icon {
            get {
                return ResourceManager.GetString("PSC icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string PSS_icon {
            get {
                return ResourceManager.GetString("PSS icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string PSV_icon {
            get {
                return ResourceManager.GetString("PSV icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Invoice Report.
        /// </summary>
        internal static string Purchase_Invoice_Report {
            get {
                return ResourceManager.GetString("Purchase Invoice Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        internal static string Purchase_Price {
            get {
                return ResourceManager.GetString("Purchase Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity In.
        /// </summary>
        internal static string Quantity_In {
            get {
                return ResourceManager.GetString("Quantity In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Out.
        /// </summary>
        internal static string Quantity_Out {
            get {
                return ResourceManager.GetString("Quantity Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Amount.
        /// </summary>
        internal static string Received_Amount {
            get {
                return ResourceManager.GetString("Received Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Location /  Branch.
        /// </summary>
        internal static string Register_Location {
            get {
                return ResourceManager.GetString("Register Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        internal static string Registration_Date {
            get {
                return ResourceManager.GetString("Registration Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration No..
        /// </summary>
        internal static string Registration_number {
            get {
                return ResourceManager.GetString("Registration number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number Required.
        /// </summary>
        internal static string Registration_Number_Required {
            get {
                return ResourceManager.GetString("Registration Number Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string Remember_me {
            get {
                return ResourceManager.GetString("Remember me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        internal static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROLES.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALES.
        /// </summary>
        internal static string SALE {
            get {
                return ResourceManager.GetString("SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoice.
        /// </summary>
        internal static string Sale_Invoice {
            get {
                return ResourceManager.GetString("Sale Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Invoice / Sale Return.
        /// </summary>
        internal static string Sale_Invoice___Sale_Return {
            get {
                return ResourceManager.GetString("Sale Invoice - Sale Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Invoice Report.
        /// </summary>
        internal static string Sale_Invoice_Report {
            get {
                return ResourceManager.GetString("Sale Invoice Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Price.
        /// </summary>
        internal static string Sale_Price {
            get {
                return ResourceManager.GetString("Sale Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string SDP_icon {
            get {
                return ResourceManager.GetString("SDP icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By.
        /// </summary>
        internal static string Search_by {
            get {
                return ResourceManager.GetString("Search by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        internal static string Secondary {
            get {
                return ResourceManager.GetString("Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of tax.
        /// </summary>
        internal static string Select_the_type_of_tax {
            get {
                return ResourceManager.GetString("Select the type of tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Settings.
        /// </summary>
        internal static string Server_Settings {
            get {
                return ResourceManager.GetString("Server Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Currency and VAT.
        /// </summary>
        internal static string Set_Currency_and_VAT {
            get {
                return ResourceManager.GetString("Set Currency and VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Company Information.
        /// </summary>
        internal static string Setup_Company_Information {
            get {
                return ResourceManager.GetString("Setup Company Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETUP FORMS.
        /// </summary>
        internal static string Setup_Forms {
            get {
                return ResourceManager.GetString("Setup Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP EMPLOYEE.
        /// </summary>
        internal static string Sign_Up_Employee {
            get {
                return ResourceManager.GetString("Sign Up Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Sign_Up_Employee_Icon {
            get {
                return ResourceManager.GetString("Sign Up Employee Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up!.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string SPP_icon {
            get {
                return ResourceManager.GetString("SPP icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start By.
        /// </summary>
        internal static string Start_By {
            get {
                return ResourceManager.GetString("Start By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start For.
        /// </summary>
        internal static string Start_For {
            get {
                return ResourceManager.GetString("Start For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START OPERATION.
        /// </summary>
        internal static string Start_Operation {
            get {
                return ResourceManager.GetString("Start Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string Start_Time {
            get {
                return ResourceManager.GetString("Start Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting date.
        /// </summary>
        internal static string Starting_date {
            get {
                return ResourceManager.GetString("Starting date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Report.
        /// </summary>
        internal static string Stock_Report {
            get {
                return ResourceManager.GetString("Stock Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Balance Report.
        /// </summary>
        internal static string Supplier_Balance_Report {
            get {
                return ResourceManager.GetString("Supplier Balance Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPPLIER DISCOUNT PRODUCTS.
        /// </summary>
        internal static string Supplier_Discount_Products {
            get {
                return ResourceManager.GetString("Supplier Discount Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Ledger Report.
        /// </summary>
        internal static string Supplier_Ledger_Report {
            get {
                return ResourceManager.GetString("Supplier Ledger Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPPLIER PRODUCT PURCHASE.
        /// </summary>
        internal static string Supplier_Product_Purchase {
            get {
                return ResourceManager.GetString("Supplier Product Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Method.
        /// </summary>
        internal static string Tax_Method {
            get {
                return ResourceManager.GetString("Tax Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax name is required.
        /// </summary>
        internal static string Tax_name_is_required {
            get {
                return ResourceManager.GetString("Tax name is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        internal static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        internal static string Terms_and_Conditions {
            get {
                return ResourceManager.GetString("Terms and Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string To_Date {
            get {
                return ResourceManager.GetString("To Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cash.
        /// </summary>
        internal static string Total_Cash {
            get {
                return ResourceManager.GetString("Total Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sale.
        /// </summary>
        internal static string Total_Sale {
            get {
                return ResourceManager.GetString("Total Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        internal static string Transaction_Type {
            get {
                return ResourceManager.GetString("Transaction Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type Stock Value.
        /// </summary>
        internal static string Transitory_Stock_Value {
            get {
                return ResourceManager.GetString("Transitory Stock Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Balance Report.
        /// </summary>
        internal static string Trial_Balance_Report {
            get {
                return ResourceManager.GetString("Trial Balance Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string TSV_icon {
            get {
                return ResourceManager.GetString("TSV icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor Auth.
        /// </summary>
        internal static string Two_Factor_Auth {
            get {
                return ResourceManager.GetString("Two Factor Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER MANAGEMENT.
        /// </summary>
        internal static string User_Management {
            get {
                return ResourceManager.GetString("User Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER ROLES.
        /// </summary>
        internal static string User_Roles {
            get {
                return ResourceManager.GetString("User Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.
        /// </summary>
        internal static string User_Roles_Icon {
            get {
                return ResourceManager.GetString("User Roles Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number is Required.
        /// </summary>
        internal static string UserId_Required {
            get {
                return ResourceManager.GetString("UserId Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        internal static string Username_is_required {
            get {
                return ResourceManager.GetString("Username is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users and Permissions.
        /// </summary>
        internal static string Users_and_Permissions {
            get {
                return ResourceManager.GetString("Users and Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        internal static string Value_Added_Tax {
            get {
                return ResourceManager.GetString("Value Added Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value added tax number required.
        /// </summary>
        internal static string Value_added_tax_number_required {
            get {
                return ResourceManager.GetString("Value added tax number required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Name.
        /// </summary>
        internal static string VAT_Name {
            get {
                return ResourceManager.GetString("VAT Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Number.
        /// </summary>
        internal static string VAT_Number {
            get {
                return ResourceManager.GetString("VAT Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Paid.
        /// </summary>
        internal static string VAT_Paid {
            get {
                return ResourceManager.GetString("VAT Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Payable.
        /// </summary>
        internal static string VAT_Payable {
            get {
                return ResourceManager.GetString("VAT Payable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat Payable Report.
        /// </summary>
        internal static string Vat_Payable_Report {
            get {
                return ResourceManager.GetString("Vat Payable Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Rate.
        /// </summary>
        internal static string VAT_Rate {
            get {
                return ResourceManager.GetString("VAT Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ware house.
        /// </summary>
        internal static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Arabic.
        /// </summary>
        internal static string Warehouse_Arabic {
            get {
                return ResourceManager.GetString("Warehouse Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse English.
        /// </summary>
        internal static string Warehouse_English {
            get {
                return ResourceManager.GetString("Warehouse English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Name.
        /// </summary>
        internal static string Warehouse_Name {
            get {
                return ResourceManager.GetString("Warehouse Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAREHOUSES.
        /// </summary>
        internal static string WarehouseTitle {
            get {
                return ResourceManager.GetString("WarehouseTitle", resourceCulture);
            }
        }
    }
}
